Replace sr3_remove with sr3d remove, change sr3d for #2 and #6

diff --git a/bin/sr3_remove b/bin/sr3_remove
--- a/bin/sr3_remove
+++ b/bin/sr3_remove
@@ -4,41 +4,44 @@ MAIN_BRANCH="main"
 
 YELLOW='\033[1;33m'
 NORMAL='\033[0m'
-echo -e "${YELLOW}[WARNING]${NORMAL} sr3_remove is deprecated. Use Git and sr3_pull instead."
+#echo -e "${YELLOW}[WARNING]${NORMAL} sr3_remove is deprecated. Use Git and sr3_pull instead."
 
-if [ $# != 1 ]; then
-    echo '[ERROR] no file to remove'
-    echo 'Usage: sr3_remove filename'
-    exit 2
-fi
+echo -e "${YELLOW}[WARNING]${NORMAL} sr3_remove is deprecated. Use sr3d remove component/config instead."
+exit 0
 
-# File must exist
-if [ ! -f "${PWD}/$1" ]; then
-    echo "[ERROR] File does not exist: ${PWD}/$1"
-    exit 3
-fi
+# if [ $# != 1 ]; then
+#     echo '[ERROR] no file to remove'
+#     echo 'Usage: sr3_remove filename'
+#     exit 2
+# fi
 
-# Directory must be controlled by Git
-if ! git status > /dev/null; then
-    echo '[ERROR] this directory is not version controlled with Git'
-    exit 4
-fi
+# # File must exist
+# if [ ! -f "${PWD}/$1" ]; then
+#     echo "[ERROR] File does not exist: ${PWD}/$1"
+#     exit 3
+# fi
 
-# Update the repository
-if ! git pull origin "${MAIN_BRANCH}"; then
-    echo "[ERROR] Problem updating local repository. Please resolve manually and retry."
-    exit 5
-fi
+# # Directory must be controlled by Git
+# if ! git status > /dev/null; then
+#     echo '[ERROR] this directory is not version controlled with Git'
+#     exit 4
+# fi
 
-# Remove the file and commit the change
-cp -p "$1" "${1}.off"
-git rm "$1"
-git commit "$1"
+# # Update the repository
+# if ! git pull origin "${MAIN_BRANCH}"; then
+#     echo "[ERROR] Problem updating local repository. Please resolve manually and retry."
+#     exit 5
+# fi
 
-if ! git push origin; then
-    echo "[ERROR] Problems were encountered during repository push."
-    exit 6
-fi
+# # Remove the file and commit the change
+# cp -p "$1" "${1}.off"
+# git rm "$1"
+# git commit "$1"
 
-# Nodes get updated from the remote Git repo
-sr3_pull
+# if ! git push origin; then
+#     echo "[ERROR] Problems were encountered during repository push."
+#     exit 6
+# fi
+
+# # Nodes get updated from the remote Git repo
+# sr3_pull
