first attempt at implementing #19

diff --git a/bin/sr3_ssh b/bin/sr3_ssh
--- a/bin/sr3_ssh
+++ b/bin/sr3_ssh
@@ -30,8 +30,20 @@ if [ -e "${ssh_user_config}" ] && { [ -z "${SSH_AUTH_SOCK}" ] || [ -z "${SSH_AGE
     unset_ssh_agent=true
 fi
 
+# numerical host, issue #19
+if [[ "$1" == "-n"* ]] ; then
+    machine_list="${git_tld}/_dsh_config/${pump_name}.list"
+    if [ ! -e "${machine_list}" ]; then
+        echo "[ERROR] dsh machine list does not exist (${machine_list})."
+        exit 4
+    fi
+    hostname="$(head ${1} ${machine_list} | tail -n1)"
+    echo "Host ${1} --> ${hostname}"
+    shift
+fi
+
 # shellcheck disable=SC2086,SC2029
-ssh ${ssh_args} "$@"
+ssh ${ssh_args} ${hostname} "$@"
 
 # Clean up ssh-agent
 if [ "${unset_ssh_agent}" = "true" ] && [ -n "${SSH_AGENT_PID}" ]; then
